version: '3.8'

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: dirnkstore-db
    environment:
      TZ: America/Argentina/Buenos_Aires
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-dirnkstore}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dirnkstore-network

volumes:
  postgres_data:
    name: dirnkstore-postgres-data

networks:
  dirnkstore-network:
    name: dirnkstore-network
